version: 2
updates:
  # Backend: Dependencias de Composer
  - package-ecosystem: "composer"
    directory: "/srcs/back"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "php"
      - "backend"
    versioning-strategy: "auto"

  # Frontend: Dependencias de npm
  - package-ecosystem: "npm"
    directory: "/srcs/front"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "javascript"
      - "frontend"
    versioning-strategy: "auto"

  # Acciones de GitHub
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "github_actions"
