name: Dependabot Auto-merge
on: pull_request

permissions:
  contents: write
  pull-requests: write
  checks: read

jobs:
  dependabot:
    name: Dependabot Auto-merge Check
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]'
    steps:
      - name: Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@v2
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"

      - name: Enable auto-merge for Dependabot PRs
        if: |
          steps.metadata.outputs.update-type == 'version-update:semver-patch' ||
          (steps.metadata.outputs.update-type == 'version-update:semver-minor' &&
           (contains(steps.metadata.outputs.dependency-names, 'composer') ||
            contains(steps.metadata.outputs.dependency-names, 'npm')))
        run: |
          gh pr review --approve "$PR_URL"
          gh pr merge --auto --merge "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GH_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: Label major updates for review
        if: steps.metadata.outputs.update-type == 'version-update:semver-major'
        run: |
          gh pr edit "$PR_URL" --add-label "major-update,needs-review"
          echo "⚠️ Major update detected. Manual review required."
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GH_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: Add component labels
        run: |
          if [[ "${{ steps.metadata.outputs.package-ecosystem }}" == "composer" ]]; then
            gh pr edit "$PR_URL" --add-label "backend"
          elif [[ "${{ steps.metadata.outputs.package-ecosystem }}" == "npm" ]]; then
            gh pr edit "$PR_URL" --add-label "frontend"
          fi
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GH_TOKEN: ${{secrets.GITHUB_TOKEN}}
