name: Generate Wiki Documentation with Docusaurus

on:
  push:
    branches:
      - development
  # Manual trigger mantenido por si acaso
  workflow_dispatch:
  # Cuando se actualiza la wiki
  repository_dispatch:
    types: [wiki_updated]

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-wiki-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          submodules: false

      - name: Checkout Wiki Content
        run: |
          git clone https://github.com/mgrl39/kaizen.wiki.git wiki-content
          ls -la wiki-content

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Initialize Docusaurus
        run: |
          npx create-docusaurus@latest temp-docs classic --typescript
          cd temp-docs
          npm install

      - name: Configure Docusaurus
        run: |
          cd temp-docs
          mkdir -p docs
          cp -r ../wiki-content/* docs/
          
          cat > docusaurus.config.js << 'EOF'
          module.exports = {
            title: 'Kaizen Wiki',
            tagline: 'Documentation from Kaizen Wiki',
            url: 'https://mgrl39.github.io',
            baseUrl: '/kaizen/',
            onBrokenLinks: 'warn',
            onBrokenMarkdownLinks: 'warn',
            favicon: 'img/favicon.ico',
            organizationName: 'mgrl39',
            projectName: 'kaizen',
            trailingSlash: false,
            presets: [
              [
                'classic',
                {
                  docs: {
                    routeBasePath: 'wiki',
                    sidebarPath: require.resolve('./sidebars.js'),
                  },
                  blog: false,
                  theme: {
                    customCss: require.resolve('./src/css/custom.css'),
                  },
                },
              ],
            ],
            themeConfig: {
              navbar: {
                title: 'Kaizen Documentation',
                items: [
                  {
                    to: '/',
                    label: 'API Docs',
                    position: 'left',
                  },
                  {
                    to: '/wiki',
                    label: 'Wiki',
                    position: 'left',
                  },
                  {
                    href: 'https://github.com/mgrl39/kaizen',
                    label: 'GitHub',
                    position: 'right',
                  },
                ],
              },
            },
          };
          EOF

      - name: Build Documentation
        run: |
          cd temp-docs
          npm run build

      - name: Prepare for Deployment
        run: |
          # Obtener la documentación actual de gh-pages
          git fetch origin gh-pages:gh-pages || true
          git checkout gh-pages || git checkout --orphan gh-pages
          
          # Mantener la documentación de Doxygen
          mkdir -p wiki
          cp -r temp-docs/build/* wiki/
          
          # Asegurar que .nojekyll existe
          touch .nojekyll

      - name: Debug Information
        run: |
          echo "Contenido del directorio actual:"
          ls -la
          echo "Contenido del directorio wiki:"
          ls -la wiki/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
          publish_branch: gh-pages
          force_orphan: false
          enable_jekyll: false
          commit_message: 'docs: update wiki documentation'
          keep_files: true
