name: Generate Doxygen Docs

on:
  push:
    branches:
      - main
      - docs
      - testing

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  generate-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Doxygen
        run: sudo apt-get install -y doxygen graphviz

      - name: Generate documentation with Doxygen
        run: |
          rm -rf docs/ html/
          doxygen Doxyfile || { echo "❌ Doxygen generation failed"; exit 1; }

          # Crear vercel.json en la raíz
          cat > vercel.json << 'EOL'
          {
            "version": 2,
            "buildCommand": false,
            "installCommand": false,
            "framework": null,
            "builds": [
              {
                "src": "html/**/*",
                "use": "@vercel/static"
              }
            ],
            "routes": [
              {
                "src": "/(.*)",
                "dest": "/html/$1"
              }
            ],
            "github": {
              "silent": true,
              "autoAlias": true
            }
          }
          EOL

          # Crear package.json en la raíz
          cat > package.json << 'EOL'
          {
            "private": true,
            "scripts": {
              "build": "echo 'No build required'"
            }
          }
          EOL

      - name: Debug Information 
        run: |
          echo "Checking deployment prerequisites..."
          echo "HTML directory exists: $(test -d html && echo 'yes' || echo 'no')"
          ls -la || true

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        env:
          ACTIONS_STEP_DEBUG: true
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
          destination_dir: .
          enable_jekyll: false
          commit_message: 'docs: update Doxygen documentation'
