name: Generate Doxygen Docs

on:
  push:
    branches:
      - main
      - docs
      - testing

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  generate-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Doxygen
        run: |
          sudo apt-get update
          sudo apt-get install -y doxygen graphviz

      - name: Generate documentation with Doxygen
        run: |
          # Limpiar directorio de docs si existe
          rm -rf docs
          
          # Generar la documentación (Doxyfile tiene configurado OUTPUT_DIRECTORY=docs)
          doxygen Doxyfile || { echo "❌ Doxygen generation failed"; exit 1; }

          # Crear .nojekyll para deshabilitar Jekyll
          touch docs/.nojekyll

          # Crear un archivo index.html de redirección si no existe
          if [ ! -f "docs/index.html" ]; then
            echo "Creando index.html de redirección..."
            cat > docs/index.html << 'EOL'
<!DOCTYPE html>
<html>
<head>
    <title>Kaizen Framework Documentation</title>
    <meta http-equiv="refresh" content="0; url=./index.html">
</head>
<body>
    <p>Redirecting to <a href="./index.html">documentation</a>...</p>
</body>
</html>
EOL
          fi

      - name: Debug Information
        run: |
          echo "Listando directorio raíz:"
          ls -la
          echo "Listando directorio docs:"
          ls -la docs/ || echo "docs/ no existe"
          echo "Verificando archivos HTML:"
          find docs -name "*.html" | head -n 5 || echo "No se encontraron archivos HTML"

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
          publish_branch: gh-pages
          force_orphan: true
          enable_jekyll: false
          commit_message: 'docs: update documentation'
