name: Generate Doxygen Docs

on:
  push:
    branches:
      - main
      - docs
      - development
      - testing

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  generate-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Doxygen
        run: |
          sudo apt-get update
          sudo apt-get install -y doxygen graphviz

      - name: Verify CSS for Doxygen
        run: |
          # Verificar que existe el directorio para los assets
          echo "Verificando directorio .github/assets..."
          if [ ! -d ".github/assets" ]; then
            echo "Creando directorio .github/assets..."
            mkdir -p .github/assets
          fi
          
          # Verificar que existe el archivo CSS
          echo "Verificando archivo doxygen-awesome.css..."
          if [ ! -f ".github/assets/doxygen-awesome.css" ]; then
            echo "⚠️ ADVERTENCIA: No se encontró el archivo .github/assets/doxygen-awesome.css, descargando de la fuente oficial..."
            curl -o .github/assets/doxygen-awesome.css https://raw.githubusercontent.com/jothepro/doxygen-awesome-css/main/doxygen-awesome.css
          fi
          
          echo "Archivo CSS disponible en: $(ls -la .github/assets/doxygen-awesome.css || echo 'No encontrado')"

      - name: Generate documentation with Doxygen
        run: |
          # Limpiar directorio de docs si existe
          rm -rf docs
          
          # Generar la documentación (Doxyfile tiene configurado OUTPUT_DIRECTORY=docs)
          doxygen Doxyfile || { echo "❌ Doxygen generation failed"; exit 1; }

          # Crear .nojekyll para deshabilitar Jekyll
          touch docs/.nojekyll

          # No es necesario crear index.html de redirección, ya que Doxygen generará su propio index.html
          # Ya que HTML_OUTPUT = . en Doxyfile, el index.html ya estará en la raíz de docs/

      - name: Debug Information
        run: |
          echo "Listando directorio raíz:"
          ls -la
          echo "Listando directorio .github/assets:"
          ls -la .github/assets/ || echo ".github/assets/ no existe"
          echo "Listando directorio docs:"
          ls -la docs/ || echo "docs/ no existe"
          echo "Verificando archivos HTML:"
          find docs -name "*.html" | head -n 5 || echo "No se encontraron archivos HTML"

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
          publish_branch: gh-pages
          force_orphan: true
          enable_jekyll: false
          commit_message: 'docs: update documentation'
          keep_files: false
