name: Internationalization Check

on:
  push:
    branches: [main, develop]
    paths:
      - "srcs/front/src/lib/i18n/**"
  pull_request:
    branches: [main, develop]
    paths:
      - "srcs/front/src/lib/i18n/**"

jobs:
  i18n-validation:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: |
          cd srcs/front
          npm ci

      - name: Check for missing translations
        run: |
          cd srcs/front
          node .github/scripts/check-translations.js

      - name: Check for unused translations
        run: |
          cd srcs/front
          node .github/scripts/find-unused-translations.js
