name: PHP Composer

on:
  push:
    branches: ["main"]
    paths:
      - "srcs/back/**"
  pull_request:
    branches: ["main"]
    paths:
      - "srcs/back/**"

permissions:
  contents: read
  security-events: write

jobs:
  backend:
    name: Laravel Backend
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: srcs/back

    steps:
      - uses: actions/checkout@v5

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"
          extensions: mbstring, xml, ctype, iconv, intl, pdo_sqlite, dom, filter, gd, json, libxml, openssl
          coverage: none
          tools: phpmd, cs2pr

      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"

      - name: Validate composer.json and composer.lock
        run: composer validate --strict

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v4
        with:
          path: srcs/back/vendor
          key: ${{ runner.os }}-php-${{ hashFiles('srcs/back/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      - name: Install dependencies
        run: |
          composer install --prefer-dist --no-progress
          php artisan key:generate

      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache

      # Análisis de código con PHPMD
      - name: Run PHPMD
        working-directory: srcs/back
        run: |
          phpmd app,routes,tests sarif phpmd.xml > phpmd-results.sarif || true
        continue-on-error: true

      # Subir resultados SARIF
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: srcs/back/phpmd-results.sarif
          category: phpmd-backend

      # Tests de PHPUnit (opcional)
      # - name: Run test suite
      #   run: vendor/bin/phpunit
